var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');
var helmet = require('helmet') ;

var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');


var app = express();

app.use(helmet()) ;



app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');



app.use(logger('tiny'));


//to add body to default request object generated by express
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
//to add cookies to default request object generated by express
app.use(cookieParser());


app.use('/static',express.static(path.join(__dirname, 'public')));
app.use('/', indexRouter);
app.use('/users', usersRouter);


// error handler
app.use(function(err, req, res, next) {
 
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};
  res.status(err.status || 500);
  res.render('error');
});

/// testing

app.listen(3000,()=>{
  console.log(`http://localhost:3000`)
})

