export const ADD_QUESTION_REQUEST = "ADD_QUESTION_REQUEST";
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS";
export const GET_INTERVIEW_REQUEST = "GET_INTERVIEW_REQUEST";
export const GET_INTERVIEW_SUCCESS = "GET_INTERVIEW_SUCCESS";
export const CREATE_INTERVIEW_REQUEST = "CREATE_INTERVIEW_REQUEST";
export const CREATE_INTERVIEW_SUCCESS = "CREATE_INTERVIEW_SUCCESS";
export const REQUEST_FAIL = "REQUEST_FAIL";